import localFont from "next/font/local";
import "./globals.css";
import Header from "@/component/Header";
import Footer from "@/component/Footer";

const Poppins = localFont({
  src: "../../public/fonts/Poppins-Regular.ttf",
  variable: "--font-Poppins-sans",
  weight: "400",
});

export const metadata = {
  title: "Dural Hukuk ve Danışmanlık Hukuk Bürosu",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
      <Header />
        {children}
      <Footer />
      </body>
    </html>
  );
}
