import GoogleComments from "@/component/GoogleComments";
import Map from "@/component/Map";
import React from "react";
import { FaEnvelope, FaPhone, FaUser } from "react-icons/fa";
import { FaMessage } from "react-icons/fa6";

export const metadata = {
  title: "Dural Hukuk - İletişim",
  description: "Generated by create next app",
};


const page = () => {
  return (
    <div>
      <div className="parallax-bg py-[50px]">
        <div className="w-[90%] md:w-full container mx-auto flex flex-col md:flex-row justify-between">
          <div className="py-[15px] md:px-[15px] md:w-[58%]">
            <h2
              className="mb-5 md:text-[32px] lg:text-[50px] font-poppins-semibold leading-[58px]"
              data-aos="fade-up"
              data-aos-duration={300}
            >
              Ön görüşme için formu doldur!
            </h2>
            <p
              className="text-[#4B4B4B] text-[18px] font-poppins"
              data-aos="fade-up"
              data-aos-duration={400}
            >
              Sizi daha fazla dinlemek, avukatlık ve danışmanlık ihtiyaçlarınıza
              odaklanmak istiyoruz. Ön görüşme için formu doldur, size dönelim.
            </p>
          </div>
          <div
            className="p-[45px] flex flex-col gap-y-4  md:w-[41%] bg-white rounded-xl shadow-lg"
            data-aos="fade-in"
            data-aos-duration={500}
          >
            <div className="flex items-center gap-x-4 border px-7 py-3 rounded-3xl">
              <FaUser className="text-gray-400" />
              <input
                type="text"
                className="w-full p-2 text-[13px] text-[#424242] outline-none rounded-xl"
                placeholder="Ad Soyad"
              />
            </div>
            <div className="flex items-center gap-x-4 border px-7 py-3 rounded-3xl">
              <FaEnvelope className="text-gray-400" />
              <input
                type="text"
                className="w-full p-2 text-[13px] text-[#424242] outline-none rounded-xl"
                placeholder="Email Adres"
              />
            </div>
            <div className="flex items-center gap-x-4 border px-7 py-3 rounded-3xl">
              <FaPhone className="text-gray-400" />
              <input
                type="text"
                className="w-full p-2 text-[13px] text-[#424242] outline-none rounded-xl"
                placeholder="Iletişim Numarası"
              />
            </div>
            <div className="flex items-center gap-x-4 border rounded-3xl h-[80px] px-3">
              <FaMessage className="text-gray-400 h-full" />
              <textarea
                className="w-full resize-none text-[13px] text-[#424242] outline-none placeholder-gray-400 bg-transparent"
                placeholder="Mesajınız"
                style={{ paddingTop: "8px" }}
              ></textarea>
            </div>
            <button className="btn transition-all duration-300">Gönder</button>
          </div>
        </div>
      </div>
      <div className="container mx-auto py-[70px]">
        <div className="grid grid-cols-1 xl:grid-cols-4 gap-x-3">
          <div
            className="rounded-[7px] shadow-lg mx-4 pt-[38px] pb-[29px] pl-[60px] pr-[20px] xl:col-span-2"
            data-aos="fade-up"
            data-aos-duration={300}
          >
            <p className="text-[24px] mb-[7px] text-[#051133] leading-7 font-poppins-semibold">
              Adres
            </p>
            <p className="text-[18px] text-[#051133] font-poppins leading-6">
              Arabacıalanı Mah. No:54 I Blok D:2022 Serdivan/Sakarya
            </p>
          </div>

          <div
            className="rounded-[7px] shadow-lg mx-4 pt-[38px] pb-[29px] pl-[60px] pr-[20px]"
            data-aos="fade-up"
            data-aos-duration={350}
          >
            <p className="text-[24px] mb-[7px] text-[#051133] leading-7 font-poppins-semibold">
              Telefon
            </p>
            <p className="text-[18px] text-[#051133] font-poppins leading-6">
              0850 532 17 45
            </p>
          </div>

          <div
            className="rounded-[7px] shadow-lg mx-4 pt-[38px] pb-[29px] pl-[60px] pr-[20px]"
            data-aos="fade-up"
            data-aos-duration={400}
          >
            <p className="text-[24px] mb-[7px] text-[#051133] leading-7 font-poppins-semibold">
              Email
            </p>
            <p className="text-[18px] text-[#051133] font-poppins leading-6">
              info@duralhukuk.com
            </p>
          </div>
        </div>
      </div>
      <GoogleComments />
      <Map />
    </div>
  );
};

export default page;
