import JoinUs from "@/component/JoinUs";
import React from "react";

export const metadata = {
  title: "Dural Hukuk - Sosyal Sorumluluk",
  description: "Generated by create next app",
};


const page = () => {
  return (
    <div
      className="container mx-auto py-20"
      data-aos="fade-in"
      data-aos-duration={500}
    >
      <div className="px-6 md:px-12 lg:px-24  font-poppins text-[#333333]">
        <h1 className="text-[#051133] font-poppins-semibold text-[28px] md:text-[32px] mb-6">
          BARO ADLİ YARDIM
        </h1>
        <p className="text-[18px] font-poppins leading-relaxed mb-4">
          Türkiye’deki her baronun Türkiye Barolar Birliği’nin talimatıyla
          oluşturmuş olduğu ve ekonomik gücü{" "}
          <strong className="font-poppins-bold">avukat</strong> tutmaya yeterli
          olmayan vatandaşlarımızın hizmetinde olan{" "}
          <strong className="font-poppins-bold">adli yardım büroları</strong>{" "}
          mevcuttur.
        </p>
        <p className="text-[18px] font-poppins leading-relaxed mb-4">
          Sakarya Barosu adli yardım bürosuna{" "}
          <strong className="font-poppins-bold">
            Sakarya’da ücretsiz avukat
          </strong>{" "}
          tutmak için başvuru yapabilirsiniz. Adli yardım başvurunuzun Sakarya
          Barosu tarafından olumlu karşılanması halinde tarafınıza baro
          tarafından{" "}
          <strong className="font-poppins-bold">ücretsiz avukat</strong> ataması
          gerçekleştirilir.
        </p>
        <p className="text-[18px] font-poppins leading-relaxed mb-4">
          Sakarya Barosu ve birçok diğer baro tarafınıza{" "}
          <strong className="font-poppins-bold">ücretsiz avukat</strong> ataması
          yapmak için aşağıdaki kriterleri kontrol etmektedir;
        </p>
        <ul className="list-disc font-poppins pl-8 text-[18px] leading-[28px]">
          <li>Fakirlik belgesi (İkametgahınızın olduğu muhtarlıktan alınır)</li>
          <li>
            Oturduğunuz ev kira ise kira sözleşmesi sureti (Ev sahibi olmanız
            adli yardım alma ihtimalinizi düşürür, kiracı olmanız arttırır)
          </li>
          <li>
            Banka mevduat hesap kayıtları (Banka hesabınızda yüklü miktarda para
            olması adli yardım alma ihtimalinizi düşürür)
          </li>
          <li>
            Adınıza kayıtlı araç olmaması (Üzerinize kayıtlı araç olması adli
            yardım alma ihtimalinizi düşürür) (E-devletten alınabilir)
          </li>
          <li>
            Sigorta tescil belgesi (İşsiz olmanız adli yardım alma ihtimalinizi
            arttırır) (E-devletten alınabilir)
          </li>
          <li>
            Adınıza kayıtlı gayrimenkul olmaması (Üzerinize kayıtlı gayrimenkul
            adli yardım alma ihtimalinizi düşürür) (E-devletten alınabilir)
          </li>
          <li>Vukuatlı nüfus kayıt sureti (E-devletten alınabilir)</li>
          <li>İkametgah (E-devletten alınabilir)</li>
        </ul>
      </div>
      <div className="w-[98%] md:w-[730px] mx-auto">
        <h2 className="font-poppins-bold text-[32px] md:text-[40px] pt-12 mb-7 text-center">
          Ücretsiz avukat tutmaya uygun musunuz?
        </h2>
        <p className="text-[18px] w-[95%] mx-auto text-[#4B4B4B] font-poppins pb-4">
          Ofisimiz avukatlık etiği gereği size yardımcı olmaktan mutluluk
          duyacaktır.
        </p>
        <JoinUs />
      </div>
    </div>
  );
};

export default page;
