import News from '@/component/News';
import React from 'react';

export const metadata = {
  title: "Dural Hukuk - Makaleler ve Haberler",
  description: "Generated by create next app",
};


const page = () => {
  return <div><News /></div>;
};

export default page;