import React from 'react';
import EkipCard from '@/component/EkipCard';
import JoinUs from '@/component/JoinUs';

export const metadata = {
  title: "Dural Hukuk - Ekibimiz",
  description: "Generated by create next app",
};

const page = () => {
  return (
   <div className='py-20 w-[90%] container mx-auto'>
    <EkipCard />
    <JoinUs />
   </div>
  );
};

export default page;